package balanc.runtime;

/**
 * The JVM backend's runtime shim (Slice 7). A generated module class (one per
 * compiled `.bal` file, emitted by {@code balanc::backend::jvm}) owns one {@code
 * Ledger} instance and posts to it by account index — the same indices the module's
 * {@code TModule.accounts} table already assigns, so no name lookup is needed at
 * runtime.
 *
 * <p>This class also carries every piece of *data-dependent* control flow the
 * generated bytecode would otherwise need a branch for: {@link #splitRatio}'s
 * largest-remainder tie-break, {@link #checkedSplitRemainder}'s bound check, and
 * {@link #report}'s per-account/per-currency inclusion logic. Keeping all of that
 * here (ordinary Java, compiled by {@code javac}) means the hand-written class file
 * writer in {@code balanc::backend::jvm} never has to emit a branch instruction or a
 * {@code StackMapTable} attribute for a generated module class — every generated
 * method is straight-line arithmetic and method calls, exactly the shape D-041
 * describes. Nothing here is Spring/Spring-Boot-specific (D-043); this class has no
 * dependency beyond the JDK itself.
 */
public final class Ledger {
    private final long[] balances;
    private final boolean[] touched;

    public Ledger(int accountCount) {
        balances = new long[accountCount];
        touched = new boolean[accountCount];
    }

    /** Posts `delta` to `account`'s running balance (debits positive, credits negative — the caller decides the sign, mirroring `eval::post`). */
    public void post(int account, long delta) {
        balances[account] += delta;
        touched[account] = true;
    }

    /**
     * T-SplitRatio's largest-remainder allocation (D-015/D-035): splits `total` in
     * ratio `aWeight : bWeight`, giving the one unit of rounding shortfall (if any) to
     * whichever side's ideal share had the larger fractional remainder, ties toward
     * `a`. Mirrors `eval::split_ratio` exactly.
     */
    public static long[] splitRatio(long total, long aWeight, long bWeight) {
        long totalWeight = aWeight + bWeight;
        long aNum = total * aWeight;
        long bNum = total * bWeight;
        long aFloor = aNum / totalWeight;
        long bFloor = bNum / totalWeight;
        long aRem = aNum % totalWeight;
        long bRem = bNum % totalWeight;
        long shortfall = total - aFloor - bFloor;
        if (aRem >= bRem) {
            return new long[] {aFloor + shortfall, bFloor};
        }
        return new long[] {aFloor, bFloor + shortfall};
    }

    /**
     * T-Split's runtime side condition (D-034): `amount` exceeding what `total` is
     * actually worth is only knowable here, at runtime — mirrors `eval`'s
     * `Code::Unbalanced` diagnostic, but as a thrown exception rather than a
     * `Diagnostic`, since a compiled module has no diagnostic-rendering pipeline of
     * its own. Returns the second half (`total - amount`); the first half is `amount`
     * itself, already known at compile time in the generated caller.
     */
    public static long checkedSplitRemainder(long total, long amount) {
        if (amount > total) {
            throw new IllegalStateException(
                    "split amount " + amount + " exceeds available money " + total);
        }
        return total - amount;
    }

    /**
     * Builds the trial balance report, mirroring `render::render_trial_balance`
     * exactly: one section per currency with at least one posting, accounts grouped
     * in `AccountKind` order (asset/liability/equity/income/expense — indices 0-4 in
     * `kindOrder`) and displayed at their normal-balance sign, with "Debit total"/
     * "Credit total" subtotals. All per-module structure (paths, grouping, currency
     * names/scales) is supplied by the generated caller as compile-time-known
     * arrays, in `TModule.accounts`/`TModule.currencies` order; only the numeric
     * balances and which accounts were ever posted to are genuinely runtime state.
     */
    public String report(
            String[] paths,
            int[] currencyIndex,
            int[] kindOrder,
            boolean[] isDebitNormal,
            String[] currencyNames,
            int[] currencyScales) {
        StringBuilder out = new StringBuilder();
        for (int c = 0; c < currencyNames.length; c++) {
            StringBuilder debitLines = new StringBuilder();
            StringBuilder creditLines = new StringBuilder();
            long debitTotal = 0;
            long creditTotal = 0;
            boolean any = false;
            for (int kind = 0; kind < 5; kind++) {
                for (int i = 0; i < paths.length; i++) {
                    if (currencyIndex[i] != c || kindOrder[i] != kind || !touched[i]) {
                        continue;
                    }
                    any = true;
                    long raw = balances[i];
                    long displayed = isDebitNormal[i] ? raw : -raw;
                    String line = "  " + padRight(paths[i], 24) + " "
                            + padLeft(format(displayed, currencyScales[c]), 12) + "\n";
                    if (isDebitNormal[i]) {
                        debitLines.append(line);
                        debitTotal += displayed;
                    } else {
                        creditLines.append(line);
                        creditTotal += displayed;
                    }
                }
            }
            if (!any) {
                continue;
            }
            out.append("Trial Balance (").append(currencyNames[c]).append(")\n");
            out.append(debitLines).append(creditLines);
            out.append("  ").append(padRight("Debit total", 24)).append(" ")
                    .append(padLeft(format(debitTotal, currencyScales[c]), 12)).append("\n");
            out.append("  ").append(padRight("Credit total", 24)).append(" ")
                    .append(padLeft(format(creditTotal, currencyScales[c]), 12)).append("\n");
        }
        return out.toString();
    }

    /** Mirrors `Amount::format` exactly: `scale` fraction digits, no point at all when `scale == 0`. */
    private static String format(long amount, int scale) {
        String sign = amount < 0 ? "-" : "";
        long abs = Math.abs(amount);
        if (scale == 0) {
            return sign + abs;
        }
        long base = 1;
        for (int i = 0; i < scale; i++) {
            base *= 10;
        }
        long whole = abs / base;
        long frac = abs % base;
        String fracStr = Long.toString(frac);
        StringBuilder padded = new StringBuilder();
        for (int i = fracStr.length(); i < scale; i++) {
            padded.append('0');
        }
        padded.append(fracStr);
        return sign + whole + "." + padded;
    }

    /** Mirrors Rust's `{:>width$}` — pads with spaces on the left, never truncates. */
    private static String padLeft(String s, int width) {
        if (s.length() >= width) {
            return s;
        }
        StringBuilder sb = new StringBuilder();
        for (int i = s.length(); i < width; i++) {
            sb.append(' ');
        }
        sb.append(s);
        return sb.toString();
    }

    /** Mirrors Rust's `{:<width$}` — pads with spaces on the right, never truncates. */
    private static String padRight(String s, int width) {
        if (s.length() >= width) {
            return s;
        }
        StringBuilder sb = new StringBuilder(s);
        for (int i = s.length(); i < width; i++) {
            sb.append(' ');
        }
        return sb.toString();
    }
}
